# Generated by Django 2.1.1 on 2018-10-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('countallfiles', models.IntegerField()),
                ('countpudmedfiles', models.IntegerField()),
                ('counttwitterfiles', models.IntegerField()),
                ('fileindex', models.TextField()),
            ],
            options={
                'db_table': 'search',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileindex', models.IntegerField(blank=True, null=True)),
                ('filetype', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sentencenum', models.IntegerField()),
                ('wordnum', models.IntegerField()),
                ('characternum', models.IntegerField()),
            ],
            options={
                'db_table': 'text',
                'managed': True,
            },
        ),
    ]
